apiVersion: v2
name: mychart
description: A simple test chart built from scratch
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "17.15.2"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
