apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{ include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- /* imagePullSecrets: render only if defined */}}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      containers:
        - name: nginx
          {{- /* use with to change context to .Values.image */}}
          {{- with .Values.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - containerPort: 80
          resources: {{ toYaml (.Values.resources | default dict) | nindent 12 }}
          env:
            - name: APP_MODE
              value: {{ .Values.env.mode | default "production" | quote }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          tolerations: {{- toYaml (.Values.tolerations | default list) | nindent 12 }} 
