apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullName" . }}
  labels: {{ include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector: 
    app: {{ include "myapp.fullName" . }}
